### PR TITLE
Save shortcut

### LINKED ISSUE #15: Save Shortcut for Forms
User should be able to submit the current form by pressing `Ctrl+Enter`

### PR DESCRIPTION
**Pull request by rishabhsingh971**
Closes #15.
Note: `native-type="submit"` must be added to `<el-button>` or `type="submit"` to `<button>`, for this shortcut to work

### CODE REVIEW

**Comment by hit12369** [comment]
Why is it needed?

**Comment by rohit-smpx** [comment]
> Why is it needed?

To enable a keyboard friendly workflow.

**Comment by hit12369** [comment]
Does anyone in the content team even need it? This is an obscure shortcut.

**Comment by rohit-smpx** [comment]
> Does anyone in the content team even need it? This is an obscure shortcut.

I think @rishabh-smpx himself needed it while testing something, key combo can be changed to something else if there is some standard.

**Comment by rishabh-smpx** [comment]
> > Does anyone in the content team even need it? This is an obscure shortcut.
> 
> I think @rishabh-smpx himself needed it while testing something, key combo can be changed to something else if there is some standard.

Yes while using Admin Panel, I felt that there is a need for a shortcut to submit because to submit we have to scroll to the bottom every time. This shortcut can save that time.

**Comment by rishabhsingh971** [comment]
As discussed with @hit12369, making a submit button `float` is better for our use case.
Closing this.

**Pull request closed without merging**
